Add functionality
YuriyFeo/react-burger-app.github.io pull request #1
Opened 2023-03-09 12:09 UTC by YuriyFeo

2023-03-09 15:37 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали отличную работу на старте вашего проекта, вёрстка корректная и аккуратная, код лаконичный и не содержит лишнего, использованы функциональные компоненты, разбитие проекта на компоненты корректное, PropTypes описаны полностью, **так держать** 👍

Тем не менее, для успешной сдачи работы на данном этапе вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**, обратив особое внимание на следующие моменты:

- Следует вынести магическое значение 27 в именованную константу `const ECK_KEYCODE = 27` в компоненте App;
- Отлично, что вынесли адрес запроса в отдельную переменную, однако следует выделить базовую часть `https://norma.nomoreparties.space/api`, т.к. она не будет изменяться от запроса к запроса и её можно будет очень удобно переиспользовать;
- У `ModalOverlay` не должно быть `children`, т.к. это просто компонент подложки. Его следует разместить рядом с контентом;
- Инлайновые стили следует использовать только в крайних случаях, когда другими методами не получается задать стилизацию объекта, следует перенести такие стили в CSS файлы в отдельные классы;

---

Также, в рамках ревью были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу, обратите на них внимание.

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления комментариев выше и указанных в коде с меткой "Надо исправить". 

---

**Успешного вам рефакторинга, хорошего настроения и отличного дня!** 🐈

2023-03-09 15:37 UTC, randomroot commented on src/components/app/app.jsx
> +      if(e.keyCode === 27){
🔴 **Нужно исправить:**

Следует вынести магическое значение 27 в именованную константу `const ECK_KEYCODE = 27`

2023-03-09 15:37 UTC, randomroot commented on src/components/app/app.jsx
> +const API = 'https://norma.nomoreparties.space/api/ingredients';
🟢 **Отлично:**
🔴 **Нужно исправить:**

Отлично, что вынесли адрес запроса в отдельную переменную, однако следует выделить базовую часть `https://norma.nomoreparties.space/api`, т.к. она не будет изменяться от запроса к запроса и её можно будет очень удобно переиспользовать;

2023-03-09 15:37 UTC, randomroot commented on src/components/app/app.jsx
> +    fetch(API)
🟡 **Можно улучшить:**

В дальнейшем добавятся ещё запросы к бэкенду, поэтому лучше вынести описание этих запросов в функции, например:

```js
function getIngredients() {
   return fetch(`${BURGER_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-03-09 15:37 UTC, randomroot commented on src/components/app/app.jsx
> +          if (res.ok) {
🟡 **Можно улучшить:**

Т.к. проверка ответа сервера и преобразование из JSON дублируется в нескольких местах, то имеет смысл вынести их в отдельную функцию:

```js
const checkResponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

2023-03-09 15:37 UTC, randomroot commented on src/components/app/app.jsx
> +  const [currentIngredient, setCurrentIngredient] = React.useState({});
🟡 **Можно улучшить:**

В качестве пустого значения не рекомендуется использовать пустой объект. Вместо этого лучше использовать `null` (или `undefined`), чтобы исключить случайные ошибки при обращении к несуществующим ключам (особенно вложенным) и обеспечить легкую проверку на наличие данных в элементе: по законам преобразования в JS соблюдается равенства `null == false`, но `{} == true` и `{ data: data } == true`.

2023-03-09 15:37 UTC, randomroot commented on src/components/app/app.jsx
> +  useEffect(() => {
🟡 **Можно улучшить:**

Данный `useEffect` целесообразно перенести в компонент `Modal`, т.к. логика по определению необходимости его закрытия архитектурно принадлежит именно ему

2023-03-09 15:37 UTC, randomroot commented on src/components/modal-overlay/modal-overlay.jsx
> +  children: PropTypes.node.isRequired,
🔴 **Нужно исправить:**

У `ModalOverlay` не должно быть `children`, т.к. это просто компонент подложки. Его следует разместить рядом с контентом:
```jsx
<>
  ....
  <ModalOverlay ... />
</>
```

2023-03-09 15:37 UTC, randomroot commented on src/components/ingredient-details/ingredient-details.jsx
> +    _id: PropTypes.string,
🟡 **Можно улучшить:**

Типизацию ингредиента целесообразно вынести в отдельную константу, чтобы переиспользовать тип в рамках всего проекта:

```js
const IngredientPropType = PropTypes.shape({ ... });

IngredientDetails.propTypes = {
  item: IngredientPropType.isRequired
}

IngredientItem.propTypes = {
  item: IngredientPropType.isRequired
}

...
```

2023-03-09 15:37 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +                <div className={`${styles.item} mb-4`} key={item.name}>
🟡 **Можно улучшить:**

Имя сейчас подходит для ключа, но в будущем целесообразно генерировать специальные идентификаторы для элемента конструкторов, т.к. могут быть повторы ингредиентов или имена окажутся одинаковыми :)

2023-03-09 15:37 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +        <Button type="primary" size="large" onClick={() => props.openModal()}>
🟡 **Можно улучшить:**

Можно воспользоваться упрощенной формой передачи в пропс без дополнительной стрелочной функции:
```js
onClick={props.openModal}
```

2023-03-09 15:37 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +function BurgerConstructor(props) {
🟡 **Можно улучшить:**

Рекомендуется использовать декомпозицию пропсов, чтобы не обращаться к переменной `props` каждый раз за нужным значением:

```jsx
function BurgerConstructor({ constructor }) {
```

Аналогично в других компонентах

2023-03-09 15:37 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +  })).isRequired,
🟡 **Можно улучшить:**

Обратите внимание, что элементы массива, если они не могут быть пустыми также следует обозначит через `isRequired`:

```js
arrayOf(item.isRequired).isRequired
```

2023-03-09 15:37 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  const tabs = [
🟡 **Можно улучшить:**

Переменную можно вынести за пределы компонента, чтобы не пересоздавать её при каждом рендере

🟢 **Отлично:**

Классно, что применили этот подход 👍

2023-03-09 15:37 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.jsx
> +      <div style={{ display: 'flex' }} className={`mb-8`}>
🔴 **Нужно исправить:**

Инлайновые стили следует использовать только в крайних случаях, когда другими методами не получается задать стилизацию объекта, следует перенести такие стили в CSS файлы в отдельные классы и задавать именно имя класса в пропс.

2023-03-09 15:37 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                data={props.ingredients.filter((el) => el.type === item.name )}
🟡 **Можно улучшить:**


Используйте useMemo, что бы фильтрация ингредиентов не вызывалась при каждом ренедере, например:
```
const buns = useMemo(data.filter((item) => item.type === 'bun'), [data]);
const mains = useMemo(data.filter((item) => item.type === 'main'), [data]);
.....
```

2023-03-09 15:37 UTC, randomroot commented on src/components/burger-ingredients-item/burger-ingredients-item.jsx
> +              <img src={item.image} alt=""/>
🟡 **Можно улучшить:**

Здесь в качестве `alt` можно задать имя ингредиента

2023-03-09 15:37 UTC, randomroot commented on src/components/ingredient-details/ingredient-details.jsx
> +      <img src={props.currentIngredient.image_large} alt="" />
🟡 **Можно улучшить:**

Здесь в качестве `alt` можно задать имя ингредиента

2023-03-09 15:37 UTC, randomroot commented on src/index.tsx
> -const root = ReactDOM.createRoot(
🟡 **Можно улучшить:**

Т.к. вы используете React 18-ой версии, то лучше оставить предыдущий вариант его инициализации:

![image](https://user-images.githubusercontent.com/15111821/224073705-4cd73119-b03a-4ae3-9358-5c7d8b49e7d0.png)

2023-03-11 10:46 UTC, YuriyFeo commented
Михаил, т.к. я тупой я не увидел ссылку на всё ревью, и использовал только пункты с сайта практикума. 

Следует вынести магическое значение 27 в именованную константу const ECK_KEYCODE = 27 в компоненте App;
Отлично, что вынесли адрес запроса в отдельную переменную, однако следует выделить базовую часть https://norma.nomoreparties.space/api, т.к. она не будет изменяться от запроса к запроса и её можно будет очень удобно переиспользовать;
У ModalOverlay не должно быть children, т.к. это просто компонент подложки. Его следует разместить рядом с контентом;
Инлайновые стили следует использовать только в крайних случаях, когда другими методами не получается задать стилизацию объекта, следует перенести такие стили в CSS файлы в отдельные классы;

2023-03-12 09:32 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, критических замечаний больше не имеется, **так держать**👍

Обратите внимание на рекомендации по **улучшению** и, по желанию, проведите их в рамках следующего PR.

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2023-03-16 10:55 UTC, merged